#!/bin/bash
#$ -S /bin/bash
#$ -N Wtdbg2
#$ -cwd
#$ -pe smp 24
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job


echo -e "Mode :$2"
echo -e "Input :$3"
echo -e "Output: $4.ctg.1.fa"
echo -e "Minimap2 option -x $5"

cd $1 
wtdbg2 -x $2 -g 1m -i $3 -o $4 -t 24 -f
wtdbg-cns -t 24 -i $4.ctg.lay.gz -fo $4.ctg.fa

minimap2 -t 24 -x $5 $4.ctg.fa $3 > temp.paf
racon $3 temp.paf $4.ctg.fa > $4.ctg.0.fa

minimap2 -t 24 -x $5 $4.ctg.0.fa $3 > temp.paf
racon $3 temp.paf $4.ctg.0.fa > $4.ctg.1.fa
