#!/bin/bash
#$ -S /bin/bash
#$ -N TA
#$ -cwd
#$ -pe smp 12
#$ -e ./logfiles/tiling_alignment.log
#$ -o ./logfiles/tiling_alignment.out
#$ -V
#$ -m e
# cargo run --release --bin alignment -- \
#       /grid/ban-m/arabidopsis_thaliana/sequel/tiling/canu/tiling.txt 0 \
#       > ./result/tiling_alignment.dat

cargo run --release --bin alignment -- \
      /grid/ban-m/arabidopsis_thaliana/sequel/tiling/canu/tiling.entire.txt 10 \
      > ./result/tiling_alignment_10.dat


