[workspace]
members = [
"disassembly",
"poa_hmm",
"bio_utils",
"last_decompose",
"last_tiling",
"variant_calling",
"create_simulation_data",
"mito_assembler",
"gfa_rust",
"de_bruijn_graph",
"histgram_viz"
]