#!/bin/bash
#$ -S /bin/bash
#$ -N MockGenomePred
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/complex1.log
#$ -o ./logfiles/complex1.log
#$ -V
#$ -m e

ROOT=${PWD}
READ=${ROOT}/data/complex/read_complex1.fa
REFERENCE=${ROOT}/data/complex/reference.fa
OUTPUT=${ROOT}/result/complex1_test
CORES=24

# ----- Alignment -----
mkdir -p ${OUTPUT}/last_db
cd ${OUTPUT}/last_db
lastdb -R00 -Q0 reference ${REFERENCE}
last-train -P${CORES} -Q0 reference ${READ} > score.matrix
lastal -f tab -P${CORES} -R00 -Q0 -p score.matrix reference ${READ} > alignments.tab
last-train -P${CORES} -Q0 reference ${REFERENCE} > reference.matrix
lastal -f tab -P${CORES} -R00 -Q0 -p reference.matrix reference ${REFERENCE} > self.tab
cd ${ROOT}

# ----- Prediction ------
./target/release/predict_mockdata \
    ${READ} ${REFERENCE} ${OUTPUT}/last_db/alignments.tab random\
    > ${OUTPUT}/predictions_random.tsv
