#!/bin/bash
#$ -S /bin/bash
#$ -N CoverageAndLK
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/coverage_and_likelihood.log
#$ -o ./logfiles/coverage_and_likelihood.out
#$ -V
#$ -m e

READ=./data/mock_genome_read.fa
REFERENCE=./data/mock_genome_ref.fa
ALIGNMENTS=./result/mock_genome/last_db/alignments.tab
CORES=24
./target/release/coverage_and_likelihood_on_simdata \
    ${READ} ${REFERENCE} ${ALIGNMENTS} \
    > ./result/coverage_and_likelihood.tsv

