#!/bin/bash
#$ -S /bin/bash
#$ -N MockGenomePred
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/mock_genome_easy.log
#$ -o ./logfiles/mock_genome_easy.log
#$ -V
#$ -m e

ROOT=${PWD}
READ=${ROOT}/data/easy/mock_genome_read.fa
REFERENCE=${ROOT}/data/easy/mock_genome_ref.fa
OUTPUT=${ROOT}/result/easy
CORES=24

# ----- Alignment -----
mkdir -p ${OUTPUT}/last_db
cd ${OUTPUT}/last_db
lastdb -R00 -Q0 reference ${REFERENCE}
last-train -P${CORES} -Q0 reference ${READ} > score.matrix
lastal -f tab -P${CORES} -R00 -Q0 -p score.matrix reference ${READ} > alignments.tab
cd ${ROOT}

# ----- Prediction ------
# ./target/release/predict_mockdata \
#     ${READ} ${REFERENCE} ${OUTPUT}/last_db/alignments.tab random\
#     > ${OUTPUT}/predictions_random.tsv
./target/release/predict_mockdata \
    ${READ} ${REFERENCE} ${OUTPUT}/last_db/alignments.tab semi\
    > ${OUTPUT}/predictions_random.tsv

