#!/bin/bash
#$ -S /bin/bash
#$ -N DecError
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/last_decompose_ev.log
#$ -o ./logfiles/last_decompose_ev.log
#$ -V
#$ -m e
set -ue
OUTPUT=./result/last_decompose_ev.txt
OUTLOG_PREFIX=./logfiles/last_decompose_ev
# RUSTFLAGS="-C target-cpu=native" cargo build --release

echo "-----start-----" >> ${OUTPUT}
# TEST_NUM=100
# COVERAGE=0
# PROBS="0.2 0.8"
# for seed in 10 20 30 40 50
# do
#     ./target/release/test_last_decompose_multiple_varying_errorate \
#         ${TEST_NUM} ${COVERAGE} ${seed} ${PROBS} >> ${OUTPUT} \
#         2>> ${OUTLOG_PREFIX}.skew.100.log
# done

TEST_NUM=100
COVERAGE=0
PROBS="0.5 0.5"
for seed in 10 20 30 40 50
do
    ./target/release/test_last_decompose_multiple_varying_errorate \
        ${TEST_NUM} ${COVERAGE} ${seed} ${PROBS} >> ${OUTPUT} \
        2>> ${OUTLOG_PREFIX}.even.100.log
done


# TEST_NUM=300
# COVERAGE=0
# PROBS="0.5 0.5"
# for seed in 10 20 30 40 50
# do
#     ./target/release/test_last_decompose_multiple_varying_errorate \
#         ${TEST_NUM} ${COVERAGE} ${seed} ${PROBS} >> ${OUTPUT} \
#         2>> ${OUTLOG_PREFIX}.even.300.log
# done

# TEST_NUM=300
# COVERAGE=0
# PROBS="0.2 0.8"
# for seed in 10 20 30 40 50
# do
#     ./target/release/test_last_decompose_multiple \
#         ${TEST_NUM} ${COVERAGE} ${seed} ${PROBS} >> ${OUTPUT}\
#         2>> ${OUTLOG_PREFIX}.skew.300.log
# done


