#!/bin/bash
#$ -S /bin/bash
#$ -N DecError
#$ -cwd
#$ -pe smp 10
#$ -e ./logfiles/last_decompose_vb.log
#$ -o ./logfiles/last_decompose_vb.log
#$ -V
#$ -m e
#$ -t 1:5
set -ue
OUTPUT=./result/last_decompose_gibbs_test_${SGE_TASK_ID}.txt
OUTLOG_PREFIX=./logfiles/last_decompose_gibbs_test_${SGE_TASK_ID}
# RUSTFLAGS="-C target-cpu=native" cargo build --release

echo "-----start-----" >> ${OUTPUT}

COVERAGE=0
PROBS="0.5 0.5"
./target/release/test_last_decompose_multiple_varying_errorate \
    $(( 1213 + $SGE_TASK_ID )) ${PROBS} >> ${OUTPUT} 2>> ${OUTLOG_PREFIX}.log

# COVERAGE=0
# PROBS="0.5 0.5"
# for seed in `seq 1 10 100`
# do
#     seed=$(( $seed + $SGE_TASK_ID ))
#     ./target/release/test_last_decompose_multiple_varying_errorate \
#         ${seed} ${PROBS} >> ${OUTPUT} \
#         2>> ${OUTLOG_PREFIX}.log
# done

# TEST_NUM=200
# COVERAGE=0
# PROBS="0.2 0.8"
# for seed in 10 20 30 40 50
# do
#     ./target/release/test_last_decompose_multiple_varying_errorate \
#         ${TEST_NUM} ${COVERAGE} ${seed} ${PROBS} >> ${OUTPUT} \
#         2>> ${OUTLOG_PREFIX}.skew.100.log
# done


# for TEST_NUM in `seq 50 10 150`
# do
#     COVERAGE=0
#     PROBS="0.5 0.5"
#     for seed in 10 20 30 40 50
#     do
#         ./target/release/test_last_decompose_multiple_varying_errorate \
#             ${TEST_NUM} ${COVERAGE} ${seed} ${PROBS} >> ${OUTPUT} \
#             2>> ${OUTLOG_PREFIX}.even.100.log
#     done
# done

# TEST_NUM=300
# COVERAGE=0
# PROBS="0.2 0.8"
# for seed in 10 20 30 40 50
# do
#     ./target/release/test_last_decompose_multiple \
#         ${TEST_NUM} ${COVERAGE} ${seed} ${PROBS} >> ${OUTPUT}\
#         2>> ${OUTLOG_PREFIX}.skew.300.log
# done


