#!/bin/bash
#$ -S /bin/bash
#$ -N DecTwo
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/last_decompose_gibbs.log
#$ -o ./logfiles/last_decompose_gibbs.log
#$ -V
#$ -m e
set -ue
OUTPUT=./result/last_decompose_gibbs.txt
OUTLOG_PREFIX=./logfiles/last_decompose_gibbs
# RUSTFLAGS="-C target-cpu=native" cargo build --release

echo "-----start-----" >> ${OUTPUT}

# ./target/release/test_last_decompose_multiple \
#     100 0 1 0.5 0.5 >> ./result/test.out \
#     2>> ./logfiles/test.log

TEST_NUM=200
COVERAGE=0
PROBS="0.2 0.8"
for seed in 10 20 30 40 50
do
    ./target/release/test_last_decompose_multiple \
        ${TEST_NUM} ${COVERAGE} ${seed} ${PROBS} >> ${OUTPUT} \
        2>> ${OUTLOG_PREFIX}.skew.200.log
done
exit 0;
TEST_NUM=100
COVERAGE=0
PROBS="0.2 0.8"
for seed in 10 20 30 40 50
do
    ./target/release/test_last_decompose_multiple \
        ${TEST_NUM} ${COVERAGE} ${seed} ${PROBS} >> ${OUTPUT} \
        2>> ${OUTLOG_PREFIX}.skew.100.log
done

TEST_NUM=100
COVERAGE=0
PROBS="0.5 0.5"
for seed in 10 20 30 40 50
do
    ./target/release/test_last_decompose_multiple \
        ${TEST_NUM} ${COVERAGE} ${seed} ${PROBS} >> ${OUTPUT} \
        2>> ${OUTLOG_PREFIX}.even.100.log
done


TEST_NUM=300
COVERAGE=0
PROBS="0.5 0.5"
for seed in 10 20 30 40 50
do
    ./target/release/test_last_decompose_multiple \
        ${TEST_NUM} ${COVERAGE} ${seed} ${PROBS} >> ${OUTPUT} \
        2>> ${OUTLOG_PREFIX}.even.300.log
done

TEST_NUM=300
COVERAGE=0
PROBS="0.2 0.8"
for seed in 10 20 30 40 50
do
    ./target/release/test_last_decompose_multiple \
        ${TEST_NUM} ${COVERAGE} ${seed} ${PROBS} >> ${OUTPUT}\
        2>> ${OUTLOG_PREFIX}.skew.300.log
done


