#!/bin/bash
#$ -S /bin/bash
#$ -N DecError
#$ -cwd
#$ -pe smp 8
#$ -e ./logfiles/last_decompose_poa.log
#$ -o ./logfiles/last_decompose_poa.log
#$ -V
#$ -m e
#$ -t 1:20
set -ue
OUTPUT=./result/last_decompose_num_poa_${SGE_TASK_ID}.txt
OUTLOG_PREFIX=./logfiles/last_decompose_num_poa_${SGE_TASK_ID}
# RUSTFLAGS="-C target-cpu=native" cargo build --release

echo "-----start-----" >> ${OUTPUT}

COVERAGE=0
PROBS="0.5 0.5"
seed=1213
seed=$(( $seed * $SGE_TASK_ID ))
./target/release/test_last_decompose_multiple_varying_errorate \
    ${seed} ${PROBS} >> ${OUTPUT} \
    2>> ${OUTLOG_PREFIX}.log

