#!/bin/bash
#$ -S /bin/bash
#$ -N DecMult
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/last_decompose_gibbs.log
#$ -o ./logfiles/last_decompose_gibbs.out
#$ -V
#$ -m e
set -ue

OUTPUT=./result/last_decompose_multi_gibbs.txt
OUTLOG_PREFIX=./logfiles/last_decompose_multi_gibbs

TEST_NUM=300
COVERAGE=0
PROBS="0.16 0.16 0.16 0.16 0.16 0.16"
RUST_LOG=debug ./target/release/test_last_decompose_multiple \
        ${TEST_NUM} ${COVERAGE} 300 0.002 ${PROBS} >> ./result/multi_test_poa_9K.tsv\
        2>> ./logfiles/multi_test_poa_9K.log
exit 0;


# TEST_NUM=240
# COVERAGE=0
# PROBS="0.16 0.16 0.16 0.16 0.16 0.16"
# ./target/release/test_last_decompose_multiple \
#     ${TEST_NUM} ${COVERAGE} 100 ${PROBS} >> ./result/multi_test_vc.tsv\
#     2>> ./logfiles/multi_test_vc.log
# exit 0;


