#!/bin/bash
#$ -S /bin/bash
#$ -N DecTwo
#$ -cwd
#$ -pe smp 12
#$ -e ./logfiles/last_decompose_gibbs.log
#$ -o ./logfiles/last_decompose_gibbs.log
#$ -V
#$ -m e
set -ue
cargo build --release 
OUTPUT=${PWD}/result/half_test_gibbs.tsv
LOGFILE=${PWD}/logfiles/half_test.tsv
echo "-----start-----" > ./result/two_test_gibbs.tsv
RUST_LOG=debug ./../target/release/test_last_decompose_multiple_lacks \
        200 0 13332 0.001 0.5 0.5 0.0 >> ${OUTPUT} 2> ${LOGFILE}
for seed in `seq 1 10`
do
    RUST_LOG=debug ./../target/release/test_last_decompose_multiple_lacks \
            60 0 ${seed} 0.001 0.5 0.5 >> ${OUTPUT} 2> ${LOGFILE}
done
