#!/bin/bash
#$ -S /bin/bash
#$ -N MockGenomePred
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/mock_genome_workflow_half2.log
#$ -o ./logfiles/mock_genome_workflow_half2.out
#$ -V
#$ -m e

ROOT=${PWD}
READ=${ROOT}/data/mock_genome_read.fa
REFERENCE=${ROOT}/data/mock_genome_ref.fa
OUTPUT=${ROOT}/result/mock_genome
CORES=24

# ----- Alignment -----
# mkdir -p ${OUTPUT}/last_db
# cd ${OUTPUT}/last_db
# lastdb -R00 -Q0 reference ${REFERENCE}
# last-train -P${CORES} -Q0 reference ${READ} > score.matrix
# lastal -f tab -P${CORES} -R00 -Q0 -p score.matrix reference ${READ} > alignments.tab
# cd ${ROOT}

# ----- Prediction ------
RUST_BACKTRACE=1 cargo run --release --bin predict_mockdata \
      -- ${READ} ${REFERENCE} ${OUTPUT}/last_db/alignments.tab\
      > ${OUTPUT}/predictions_half.tsv

