#!/bin/bash
#$ -S /bin/bash
#$ -N Simulation
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/log
#$ -o ./logfiles/out
#$ -V
#$ -m e

ROOT=${PWD}
READ=${ROOT}/data/mito_mutant_simulate.fastq
REFERENCE=${ROOT}/data/reference.fa
OUTPUT=${ROOT}/result
CORES=24

# ----- Alignment -----
cat ${READ} | paste - - - - | cut -f 1,2 | \
    sed -e 's/@/>/g' | tr '\t' '\n' \
                          > ${ROOT}/data/mito_mutant_simulate.fasta
READ=${ROOT}/data/mito_mutant_simulate.fasta

mkdir -p ${OUTPUT}/last_db
cd ${OUTPUT}/last_db
lastdb -R00 -Q0 reference ${REFERENCE}
last-train -P${CORES} -Q0 reference ${READ} > score.matrix
lastal -f -P${CORES} -R00 -Q0 -p score.matrix reference ${READ} > alignments.tab
cd ${ROOT}

# ----- Prediction ------
cargo run --release --bin predicte -- ${READ} ${REFERENCE} \
      ${OUTPUT}/last_db/alignments.tab ${CORES} \
      > ${OUTPUT}/predictions.tsv

