#!/bin/bash
#$ -S /bin/bash
#$ -N MockGenomePred
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/yg.log
#$ -o ./logfiles/yg.log
#$ -V
#$ -m e

ROOT=${PWD}
READ=$1
REFERENCE=$2
OUTPUT=$3
CORES=24


# ----- Alignment -----
if [ -d ${OUTPUT} ]
then
    echo "Removing previous results..."
    rm -r ${OUTPUT}
fi
mkdir -p ${OUTPUT}/last_db
cd ${OUTPUT}/last_db
lastdb -R00 -Q0 reference ${REFERENCE}
last-train -P${CORES} -Q0 reference ${READ} > score.matrix
lastal -f tab -P${CORES} -R00 -Q0 -p score.matrix reference ${READ} > alignments.tab
last-train -P${CORES} -Q0 reference ${REFERENCE} > reference.matrix
lastal -f tab -P${CORES} -R00 -Q0 -p reference.matrix reference ${REFERENCE} > self.tab
cd ${ROOT}

# ----- Prediction ------
./target/release/yellowgate \
    ${READ}\
    ${REFERENCE} \
    ${OUTPUT}/last_db/alignments.tab \
    ${OUTPUT}/last_db/self.tab \
    ${OUTPUT} > ${OUTPUT}/yg.out 2> ${OUTPUT}/yg.log

