#!/bin/bash
#$ -S /bin/bash
#$ -N CalcP
#$ -cwd
#$ -pe smp 1
#$ -e ./logfiles/calc_p_value.log
#$ -o ./logfiles/calc_p_value.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job
## "-S" specifies which shell do the script run on.
## "-N" specifies the name of the job(should NOT be TEMPLATE).
## "-cwd" means the script run on the current directly, not on $HOME.
## "-pe smp N" specifies the number of the core the script requires.
## with "-e [path]", the stderr would be written in [path], not ${HOME}/$JOB_NUMBER
## with "-o [path]" is the same as "-e", except for stdout.
## with "-V", all envirnmental variables would be inherited.
## "with -m e", a mail would be sent if the job halt with an error.
## For more detail, see `man qsub`
BAM=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/mapback/guided_asm_sequel_canu.contigs.fasta.mapback.bam
SUBST_RATE=0.05
cargo run --release --bin calc_p_value_at_each_position -- ${BAM} ${SUBST_RATE} > ./result/sequel_canu_P_value.tsv
