#!/bin/bash
#$ -S /bin/bash
#$ -N CalcP
#$ -cwd
#$ -pe smp 1
#$ -e ./logfiles/calc_p_value.log
#$ -o ./logfiles/calc_p_value.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job
## "-S" specifies which shell do the script run on.
## "-N" specifies the name of the job(should NOT be TEMPLATE).
## "-cwd" means the script run on the current directly, not on $HOME.
## "-pe smp N" specifies the number of the core the script requires.
## with "-e [path]", the stderr would be written in [path], not ${HOME}/$JOB_NUMBER
## with "-o [path]" is the same as "-e", except for stdout.
## with "-V", all envirnmental variables would be inherited.
## "with -m e", a mail would be sent if the job halt with an error.
## For more detail, see `man qsub`

CANU_MAPBACK=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/mapback/guided_asm_sequel_canu.contigs.fasta.mapback.bam
WTDBG_MAPBACK=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/mapback/wtdbg2_sequel.ctg.1.fa.mapback.bam
FLYE_MAPBACK=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/mapback/scaffolds.fasta.mapback.bam
SUBST_RATE=0.05

cargo run --release --bin calc_p_value_at_each_position -- ${CANU_MAPBACK} ${SUBST_RATE} > ./result/sequel_canu_P_value.tsv
Rscript --slave --vanilla ./script/calc_p_value.R \
  ./result/sequel_canu_P_value.tsv \
  sequel_canu_pvalue
  
cargo run --release --bin calc_p_value_at_each_position -- ${FLYE_MAPBACK} ${SUBST_RATE} > ./result/sequel_flye_P_value.tsv
Rscript --slave --vanilla ./script/calc_p_value.R \
  ./result/sequel_flye_P_value.tsv \
  sequel_flye_pvalue

cargo run --release --bin calc_p_value_at_each_position -- ${WTDBG_MAPBACK} ${SUBST_RATE} > ./result/sequel_wtdbg_P_value.tsv
Rscript --slave --vanilla ./script/calc_p_value.R \
  ./result/sequel_wtdbg_P_value.tsv \
  sequel_wtdbg_pvalue
