#!/bin/bash
#$ -S /bin/bash
#$ -N pickup
#$ -cwd
#$ -pe smp 1
#$ -e ./logfiles/canu_sequel_trimed_reads.log
#$ -o ./logfiles/canu_sequel_trimed_reads.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job
## "-S" specifies which shell do the script run on.
## "-N" specifies the name of the job(should NOT be TEMPLATE).
## "-cwd" means the script run on the current directly, not on $HOME.
## "-pe smp N" specifies the number of the core the script requires.
## with "-e [path]", the stderr would be written in [path], not ${HOME}/$JOB_NUMBER
## with "-o [path]" is the same as "-e", except for stdout.
## with "-V", all envirnmental variables would be inherited.
## "with -m e", a mail would be sent if the job halt with an error.
## For more detail, see `man qsub`

mkdir -p ./result/sequel_canu_tail/
fatt name /data/ban-m/a_thaliana/sequel_reads/sequel1_filter_dedupe.fq | \
    grep -e "62784440" \
         -e "44696477" \
         -e "19202344" \
         -e "49414793" \
         -e "29819225" \
         -e "53084829" > ./result/sequel_canu_tail/names.txt
fatt extract --file ./result/sequel_canu_tail/names.txt /data/ban-m/a_thaliana/sequel_reads/sequel1_filter_dedupe.fq \
     > ./result/sequel_canu_tail/reads.fq

         
