#!/bin/bash
#$ -S /bin/bash
#$ -N compare_mapback
#$ -cwd
#$ -pe smp 1
#$ -e ./logfiles/compare_mapbacks.log
#$ -o ./logfiles/compare_mapbacks.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job
EVALUATE=~/work/arabidopsis_mitochondria/select_mitochondrial_genome/target/release/evaluate

FIRST=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/filtered_reads.fq
CANU_MAPBACK=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/mapback/guided_asm_sequel_canu.contigs.fasta.mapback.bam
WTDBG_MAPBACK=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/mapback/wtdbg2_sequel.ctg.1.fa.mapback.bam
FLYE_MAPBACK=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/mapback/scaffolds.fasta.mapback.bam

cat ${FIRST} | paste - - - - | cut -f 1 |\
    sed -e 's/@//g' > ./result/filtered_name.txt
samtools view ${CANU_MAPBACK} | cut -f 1 > ./result/canu_mapback_name.txt
samtools view ${WTDBG_MAPBACK} | cut -f 1  > ./result/wtdbg_mapback_name.txt
samtools view ${FLYE_MAPBACK} | cut -f 1 > ./result/flye_mapback_name.txt

${EVALUATE} ./result/filtered_name.txt ./result/canu_mapback_name.txt > ./result/canu_diff.txt
${EVALUATE} ./result/filtered_name.txt ./result/wtdbg_mapback_name.txt > ./result/wtdbg_diff.txt
${EVALUATE} ./result/filtered_name.txt ./result/flye_mapback_name.txt > ./result/flye_diff.txt
