#!/bin/bash
#$ -S /bin/bash
#$ -N compare_mapback
#$ -cwd
#$ -pe smp 1
#$ -e ./logfiles/compare_mapbacks.log
#$ -o ./logfiles/compare_mapbacks.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job
## "-S" specifies which shell do the script run on.
## "-N" specifies the name of the job(should NOT be TEMPLATE).
## "-cwd" means the script run on the current directly, not on $HOME.
## "-pe smp N" specifies the number of the core the script requires.
## with "-e [path]", the stderr would be written in [path], not ${HOME}/$JOB_NUMBER
## with "-o [path]" is the same as "-e", except for stdout.
## with "-V", all envirnmental variables would be inherited.
## "with -m e", a mail would be sent if the job halt with an error.
## For more detail, see `man qsub`
EVALUATE=~/work/arabidopsis_mitochondria/select_mitochondrial_genome/target/release/evaluate

FIRST=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/filtered_reads.fq
CANU_MAPBACK=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/mapback/guided_asm_sequel_canu.contigs.fasta.mapback.bam
WTDBG_MAPBACK=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/mapback/wtdbg2_sequel.ctg.1.fa.mapback.bam
FLYE_MAPBACK=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/mapback/scaffolds.fasta.mapback.bam

cat ${FIRST} | paste - - - - | cut -f 1 |\
    sed -e 's/@//g' > ./result/filtered_name.txt
samtools view ${CANU_MAPBACK} | cut -f 1 > ./result/canu_mapback_name.txt
samtools view ${WTDBG_MAPBACK} | cut -f 1  > ./result/wtdbg_mapback_name.txt
samtools view ${FLYE_MAPBACK} | cut -f 1 > ./result/flye_mapback_name.txt

${EVALUATE} ./result/filtered_name.txt ./result/canu_mapback_name.txt > ./result/canu_diff.txt
${EVALUATE} ./result/filtered_name.txt ./result/wtdbg_mapback_name.txt > ./result/wtdbg_diff.txt
${EVALUATE} ./result/filtered_name.txt ./result/flye_mapback_name.txt > ./result/flye_diff.txt
