#!/bin/bash
#$ -S /bin/bash
#$ -N MapBack
#$ -cwd
#$ -pe smp 12
#$ -e ./logfiles/mapback_after_breaking.log
#$ -o ./logfiles/mapback_after_breaking.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job
set -ue 

## ===== Variables ======
CONTIG=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/canu/guided_asm_sequel_canu.contigs.fasta
READS=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/filtered_reads.fq
OVERLAP_LENGTH=30700

## ===== Outputs ======
OUTPUT_DIR=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/mapback_after_split
SPLIT_CONTIG=${OUTPUT_DIR}/guided_asm_sequel_canu_split.contigs.fasta
MAPPINGS=${OUTPUT_DIR}/guided_asm_sequel_canu_split.contigs.mapback.bam
MAPPINGS_SUB=${OUTPUT_DIR}/guided_asm_sequel_canu_split.contigs.mapback.sub.bam
WIG=${OUTPUT_DIR}/guided_asm_sequel_canu_split.contigs.mapback.wig
TARBALL=${OUTPUT_DIR}/split_alignment.tar.gz

## ==== Split contigs into two and concat them
mkdir -p ${OUTPUT_DIR}
cargo run --release --bin split_at_half -- ${CONTIG} ${OVERLAP_LENGTH} > ${SPLIT_CONTIG}
minialign -x pacbio -t 12 ${SPLIT_CONTIG} ${READS}  | samtools view -Shb | \
    samtools sort -m 5G -@ 12 -O BAM > ${MAPPINGS}
samtools index ${MAPPINGS}
samtools view -Shb  ${MAPPINGS} tig00000003 | \
    samtools sort -m 5G -@ 12 -OBAM > ${MAPPINGS_SUB}
samtools depth ${MAPPINGS} > ${WIG}
# Rscript --vanilla --slave ./script/coverage.R ${WIG} 
