#!/bin/bash
#$ -S /bin/bash
#$ -N MockGenome
#$ -cwd
#$ -pe smp 1
#$ -V
#$ -e ./logfiles/mock.log
#$ -o ./logfiles/mock.out
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job
set -ue

### Variables

OUTPUT=/grid/ban-m/create_simulated_genome


### ==== Preprocess =====

# rm -rf ${OUTPUT} 
# mkdir -p ${OUTPUT}

function procedure(){
    READS=$1
    OUTDIR=${OUTPUT}/$2
    mkdir -p ${OUTDIR}
    #### ==== Canu =====
    rm -rf ${OUTDIR}/canu
    mkdir -p ${OUTDIR}/canu
    qsub -sync yes -o ./logfiles/canu_${2}.out \
         -e ./logfiles/canu_${2}.log \
         ./script/canu.job \
         ${OUTDIR}/canu \
         ${2}_canu \
         -pacbio-raw \
         ${READS}
    exit 0;
    #### ==== Wtdbg2 =====
    rm -rf ${OUTDIR}/wtdbg2
    mkdir -p ${OUTDIR}/wtdbg2
    qsub -sync yes -o ./logfiles/wtdbg2_${2}.out \
         -e ./logfiles/wtdbg2_${2}.log \
         ./script/wtdbg2.job \
         ${OUTDIR}/wtdbg2 \
         ont \
         ${READS} \
         wtdbg2_${2} \
         map-ont 
    #### ===== Flye =======
    rm -rf ${OUTDIR}/flye
    mkdir -p ${OUTDIR}/flye
    qsub -sync yes -o ./logfiles/flye_${2}.out \
         -e ./logfiles/flye_${2}.log \
         ./script/flye.job \
         nano-raw \
         ${READS} \
         ${OUTDIR}/flye 
}

# procedure ${PWD}/../create_simulation_data/data/mock_genome_read.fq mock_genome 
# procedure ${PWD}/../create_simulation_data/data/complex/read_complex1.fq complex1  
# procedure ${PWD}/../create_simulation_data/data/complex/read_complex2.fq complex2 
procedure ${PWD}/../create_simulation_data/data/long_hard/reads.fq long_hard 
# procedure ${PWD}/../create_simulation_data/data/flip_repeats/forward_repeat.fastq forward_repeat 
# procedure ${PWD}/../create_simulation_data/data/flip_repeats/reverse_repeat.fastq reverse_repeat

