#!/bin/bash
#$ -S /bin/bash
#$ -N racon
#$ -cwd
#$ -pe smp 12
#$ -e ./logfiles/racon.log
#$ -o ./logfiles/racon.log
#$ -V
#$ -m e
set -ue
OUTPUT=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/temp/
mkdir -p ${OUTPUT}
CANU=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/canu/guided_asm_sequel_canu.contigs.fasta
FLYE=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/flye/scaffolds.fasta
WTDBG=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/wtdbg2/wtdbg2_sequel.ctg.1.fa
RA=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/ra/guided_asm_sequel_ra.fa
FALCON=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/FALCON/2-asm-falcon/p_ctg.fa

READ=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/filtered_reads.fq
cd ${OUTPUT}
function polish(){
    input=$1
    outname=$2
    number=$3
    minimap2 -t 12 -x map-pb ${input} ${READ} > ${outname}.${number}.paf
    racon -t 12 -u ${READ} ${outname}.${number}.paf ${input} > ${outname}.${number}.fa
    rm *.paf
}

cp ${CANU}  ./canu.0.fa
cp ${FLYE} ./flye.0.fa 
cp ${WTDBG}  wtdbg.0.fa 
cp ${RA} ./ra.0.fa 
cp ${FALCON} ./falcon.0.fa

for i in 1 2 3 4 5
do
    for ctg in canu flye wtdbg ra falcon
    do
        polish ${ctg}.$((i-1)).fa ${ctg} ${i}
    done
done
