#!/bin/bash
#$ -S /bin/bash
#$ -N selectpileup
#$ -cwd
#$ -pe smp 10
#$ -e ./logfiles/select_pileup.log
#$ -o ./logfiles/select_pileup.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job
## "-S" specifies which shell do the script run on.
## "-N" specifies the name of the job(should NOT be TEMPLATE).
## "-cwd" means the script run on the current directly, not on $HOME.
## "-pe smp N" specifies the number of the core the script requires.
## with "-e [path]", the stderr would be written in [path], not ${HOME}/$JOB_NUMBER
## with "-o [path]" is the same as "-e", except for stdout.
## with "-V", all envirnmental variables would be inherited.
## "with -m e", a mail would be sent if the job halt with an error.
## For more detail, see `man qsub`

# ====== Variables ======
FLYE_MAPBACK=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/mapback/scaffolds.fasta.mapback.bam
CANU_MAPBACK=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/mapback/guided_asm_sequel_canu.contigs.fasta.mapback.bam
WTDBG2_MAPBACK=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/mapback/wtdbg2_sequel.ctg.1.fa.mapback.bam
OUTPUT=/grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/mapback_select
mkdir -p ${OUTPUT}

# ======= Flye ======
CONTIG="contig_4"
START=47830
END=47830
cargo run --release --bin select_from_pileup -- \
      ${FLYE_MAPBACK} ${CONTIG} ${START} ${END} | \
    samtools sort -m 5G -@ 10 -O BAM > ${OUTPUT}/flye.bam
samtools index ${OUTPUT}/flye.bam

# ===== Canu =====
CONTIG="tig00000010"
START=33462
END=50193
# cargo run --release --bin select_from_pileup -- \
#       ${CANU_MAPBACK} ${CONTIG} ${START} ${END} |\
#     samtools sort -m 5G -@ 10 -O BAM > ${OUTPUT}/canu_passing_through_repeat.bam

START=305448
# cargo run --release --bin select_from_pileup_end \
#       ${CANU_MAPBACK} ${CONTIG} ${START} |\
#     samtools sort -m 5G -@ 10 -O BAM > ${OUTPUT}/canu_dna_non_circular.bam


# ===== WTDBG2 ======
CONTIG="ctg1"
START=45600
END=82650
# cargo run --release --bin select_from_pileup -- \
#       ${WTDBG2_MAPBACK} ${CONTIG} ${START} ${END} |\
#     samtools sort -m 5G -@ 10 -O BAM > ${OUTPUT}/wtdbg2_do_exists.bam



