#!/bin/bash
#$ -S /bin/bash
#$ -N SvS
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/clip_self_chimera.log
#$ -o ./logfiles/clip_self_chimera.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job
## "-S" specifies which shell do the script run on.
## "-N" specifies the name of the job(should NOT be TEMPLATE).
## "-cwd" means the script run on the current directly, not on $HOME.
## "-pe smp N" specifies the number of the core the script requires.
## with "-e [path]", the stderr would be written in [path], not ${HOME}/$JOB_NUMBER
## with "-o [path]" is the same as "-e", except for stdout.
## with "-V", all envirnmental variables would be inherited.
## "with -m e", a mail would be sent if the job halt with an error.
## For more detail, see `man qsub`

# cargo run --release --bin alignment -- /grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/filtered_reads.fq > ./result/self_vs_self.tsv

cargo run --release --bin clip_self_chimera -- \
      /grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/filtered_reads.fq \
      > /grid/ban-m/arabidopsis_thaliana/sequel/guided_asm/filtered_reads_remove_chimera.fq
