#!/bin/bash
#$ -S /bin/bash
#$ -N Tiling
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/tiling_by_stiff_sequence.log
#$ -o ./logfiles/tiling_by_stiff_sequence.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
set -ue
READS=$1
CONTIGS=$2
PEAKS=$3
OUTPUT=$4
PREFIX=$5
ROOT=$PWD

mkdir -p ${OUTPUT}/${PREFIX}
# cargo run --release --bin split_contig_by_peak -- ${CONTIGS} ${PEAKS} > ${OUTPUT}/${PREFIX}.split.contigs
# mkdir -p ${OUTPUT}/${PREFIX}
# cd $OUTPUT/${PREFIX}
# lastdb -uNEAR -P 24 -R11 ${PREFIX} ${OUTPUT}/${PREFIX}.split.contigs
# lastal -Q1  -f TAB -P 12 ${PREFIX} ${READS} > mappings.tab
# cd ${ROOT}
# cargo run --release --bin tiling -- \
#       ${OUTPUT}/${PREFIX}/mappings.tab > \
#       ${OUTPUT}/${PREFIX}/tiling.txt



cd ${OUTPUT}/${PREFIX}
# lastdb -uNEAR -P 24 -R 11 ${PREFIX}.entire ${CONTIGS}
# lastal -Q1 -f TAB -P 12 ${PREFIX}.entire ${READS}  > mappings.entire.tab
cd ${ROOT}
cargo run --release --bin tiling_with_configure -- \
      ${OUTPUT}/${PREFIX}/mappings.entire.tab \
      ${PEAKS} > \
      ${OUTPUT}/${PREFIX}/tiling.entire.txt
