#!/bin/bash
#$ -S /bin/bash
#$ -N Tiling
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/tiling_by_stiff_sequence.log
#$ -o ./logfiles/tiling_by_stiff_sequence.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job
## "-S" specifies which shell do the script run on.
## "-N" specifies the name of the job(should NOT be TEMPLATE).
## "-cwd" means the script run on the current directly, not on $HOME.
## "-pe smp N" specifies the number of the core the script requires.
## with "-e [path]", the stderr would be written in [path], not ${HOME}/$JOB_NUMBER
## with "-o [path]" is the same as "-e", except for stdout.
## with "-V", all envirnmental variables would be inherited.
## "with -m e", a mail would be sent if the job halt with an error.
## For more detail, see `man qsub`
set -ue
READS=$1
CONTIGS=$2
PEAKS=$3
OUTPUT=$4
PREFIX=$5

mkdir -p ${OUTPUT}
cargo run --release --bin split_contig_by_peak -- ${CONTIGS} ${PEAKS} > ${OUTPUT}/${PREFIX}.split.contigs
mkdir -p ${OUTPUT}/${PREFIX}
cd $OUTPUT/${PREFIX}
lastdb -uNEAR -P 24 -R11 ${PREFIX} ${OUTPUT}/${PREFIX}.split.contigs
lastal -Q1  -f TAB -P 12 ${PREFIX} ${READS} > mappings.tab

# lastdb -uNEAR -P 24 -R 11 ${PREFIX}.entire ${CONTIGS}
# lastal -Q1 -f TAB -P 12 ${PREFIX}.entire ${READS}  > mappings.entire.tab

