#!/bin/bash
#$ -S /bin/bash
#$ -N trim_region
#$ -cwd
#$ -pe smp 1
#$ -e ./logfiles/trim_genomic_region.log
#$ -o ./logfiles/trim_genomic_region.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job

REGION="1:1000000-1500000"
SEQUEL=/grid/ban-m/arabidopsis_thaliana/sequel/mapping/sequel_minimap2.bam
ONT=/grid/ban-m/arabidopsis_thaliana/nanopore/mapping/nanopore_minimap2.bam

samtools depth -r ${REGION} ${SEQUEL} > ./data/sequel_chr01_1000K_1500K.wig
samtools depth -r ${REGION} ${ONT}  > ./data/ont_chr01_1000K_1500K.wig

Rscript --vanilla --slave ./script/trim_genomic_region.R ./data/sequel_chr01_1000K_1500K.wig ./data/ont_chr01_1000K_1500K.wig
