#!/bin/bash
#$ -S /bin/bash
#$ -N PickExample
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/pick_exampler.log
#$ -o ./logfiles/pick_exampler.out
#$ -V
#$ -m e
ASSIGNMENT=./result/sequel_minimap2_assignment.tsv
if [ ! -e ${ASSIGNMENT} ]
then
    qsub ./script/sam_to_annotation.job
fi
SELECT=./result/sequel_minimap2_select.tsv
if [ ! -e ${SELECT} ]
then
    cat ${ASSIGNMENT} | awk '($2 ~ /mito.*/)' | head -n2 > ./result/sequel_minimap2_select.tsv
    cat ${ASSIGNMENT} | awk '($2 ~ /chlo.*/)' | head -n2 >> ./result/sequel_minimap2_select.tsv
    cat ${ASSIGNMENT} | awk '($2 ~ [0-9])'    | head -n2 >> ./result/sequel_minimap2_select.tsv
    cat ${ASSIGNMENT} | awk '($2 == "*")'     | head -n2 >> ./result/sequel_minimap2_select.tsv
fi


# INPUT=/grid/ban-m/test.fq
INPUT=/data/ban-m/a_thaliana/sequel_reads/sequel1_filter_dedupe.fq
k=16
for k in 10 16 17 18 20 30
do
    # cargo run --release --bin pick_exampler -- ${INPUT} 24 ${k} ${ASSIGNMENT} \
    #       > ./result/${k}_exampler.dat
    cargo run --release --bin pick_exampler_full -- ${INPUT} 24 ${k} ${ASSIGNMENT} \
          > ./result/${k}_exampler_select.dat
done


