#!/bin/bash
#$ -S /bin/bash
#$ -N RoundCount
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/round_count.log
#$ -o ./logfiles/round_count.out
#$ -V
#$ -m e


INPUT=/grid/ban-m/test.fa
k=16
max_dist=3
SELECT=result/sequel_minimap2_select.tsv
for k in 10 16 20 30
do
    # cargo run --release --bin round_count -- ${INPUT} 24 ${k} ${max_dist} > ./result/${k}_${max_dist}.json
    cargo run --release --bin round_count_on_read ${INPUT} 24 ${k} ${max_dist} ${SELECT} 
done

