#!/bin/bash
#$ -S /bin/bash
#$ -N Convert
#$ -cwd
#$ -pe smp 12
#$ -e ./logfiles/convert.log
#$ -o ./logfiles/convert.out

ROOT=/grid/ban-m/arabidopsis_thaliana/sequel/assemble/mine
LASTTAB=${ROOT}/last_db/initial.tab
READ=${ROOT}/filtered_read.fasta
CONTIGS=${ROOT}/initial_asm/scaffolds.fasta
cargo run --release --bin encode -- ${LASTTAB} ${CONTIGS} ${READ} ./data/mine_contig.json ./data/mine_reads.json \
      2> ./logfiles/test.log  > ./logfiles/test.out
cargo run --release --bin convert_to_d3_data -- ./data/mine_contig.json ./data/mine_reads.json > ./data/mine_d3.json

