#!/bin/bash
#$ -S /bin/bash
#$ -N Convert
#$ -cwd
#$ -pe smp 12
#$ -e ./logfiles/rep_trimmed.log
#$ -o ./logfiles/rep_trimmed.out
#$ -V
set -ue
ROOT=/grid/ban-m/arabidopsis_thaliana/sequel/assemble/mine
LASTTAB=${ROOT}/last_db/collupsed.tab
READ=${ROOT}/filtered_read.fasta
CONTIGS=${ROOT}/contigs.fasta
SELF_LASTTAB=${ROOT}/last_db/self_no_repeat.tab
PREFIX=./data/mine_no_repeat
cargo run --release --bin annotate_dotplot -- ${CONTIGS} ${SELF_LASTTAB} \
      > ${PREFIX}_repeats.json
cargo run --release --bin encode \
      -- ${LASTTAB} ${CONTIGS} ${READ} ${PREFIX}_repeats.json \
      ${PREFIX}_contig.json ${PREFIX}_reads.json 
cargo run --release --bin convert_to_d3_data \
      -- ${PREFIX}_contig.json ${PREFIX}_reads.json \
      > ${PREFIX}_d3.json

