#!/bin/bash
#$ -S /bin/bash
#$ -N M4
#$ -cwd
#$ -pe smp 24
#$ -o ./logfiles/M4.out
#$ -e ./logfiles/M4.log
#$ -V
#$ -m e

## ---- Variables ----
set -ue
READS=$1
OUTPATH=$2
REFERENCE=$3


## ---- LAST ALIGNMENTS -----

cargo build --release 
ROOT=$PWD
mkdir -p ${OUTPATH}/last_db
cd ${OUTPATH}/last_db
lastdb -P 24 -Q0 -R 00 reference ${REFERENCE}
last-train -P 24 -Q0 reference ${REFERENCE} > self.matrix
lastal -Q0 -f TAB -P 24 reference ${REFERENCE} -p self.matrix -R 00 > self.tab
last-train -P 24 reference ${READS} > reads.matrix
lastal -Q0 -f TAB -R00 -P 24 reference ${READS} -p reads.matrix |\
    last-split | maf-convert tab -j 600 > reads.tab
cd ${ROOT}
./target/release/mmmm --alignments ${OUTPATH}/last_db/reads.tab \
                      --output ${OUTPATH}/m4 \
                      --reads ${READS}\
                      --contigs ${REFERENCE}\
                      --self_alignments ${OUTPATH}/last_db/self.tab \
                      1> ${OUTPATH}/m4.out 2> ${OUTPATH}/m4.log
