#!/bin/bash
#$ -S /bin/bash
#$ -N YG
#$ -cwd
#$ -pe smp 24
#$ -o ./logfiles/YG.out
#$ -e ./logfiles/YG.log
#$ -V
#$ -m e

## ---- Variables ----
set -ue
READS=$1
OUTPATH=$2
REFERENCE=$3


## ---- LAST ALIGNMENTS -----

cargo build --release 
ROOT=$PWD
mkdir -p ${OUTPATH}/last_db
cd ${OUTPATH}/last_db
lastdb -P 24 -Q0 -R 00 reference ${REFERENCE}
last-train -P 24 -Q0 reference ${REFERENCE} > self.matrix
lastal -Q0 -f TAB -P 24 reference ${REFERENCE} -p self.matrix -R 00 > self.tab
last-train -P 24 reference ${READS} > reads.matrix
lastal -Q0 -f TAB -R00 -P 24 reference ${READS} -p reads.matrix > reads.tab
cd ${ROOT}
cargo run --release --bin yellowgate -- \
      --alignments ${OUTPATH}/last_db/reads.tab \
      --output ${OUTPATH}/yg \
      --reads ${READS}\
      --contigs ${REFERENCE}\
      --self_alignments ${OUTPATH}/last_db/self.tab \
      1> ${OUTPATH}/yg.out 2> ${OUTPATH}/yg.log
      
