#!/bin/bash
#$ -S /bin/bash
#$ -N gen_msa
#$ -cwd
#$ -pe smp 1
#$ -e ./logfiles/gen_msa.log
#$ -o ./logfiles/gen_msa.log
#$ -V

LENGTH=1000
READ_NUM=100
SUBST_RATE=0.04

for variant_rate in 0.01 0.02 0.03 0.10 0.11
do
    for mix_rate in 0.01 0.10 0.2 0.3 0.5
    do
        cargo run --release --bin generate_msa ${LENGTH} ${READ_NUM} ${variant_rate} ${mix_rate} ${SUBST_RATE} ${variant_rate}_${mix_rate}_ans.tsv > ./data/${variant_rate}_${mix_rate}_seq.txt
    done
done
