#!/bin/bash

ROOT=/work/ban-m/arabidopsis_mitochondria/create_simulation_data/data
OUTPUT=${PWD}/result
qsub -o ./logfiles/complex1.log -j y ./script/disassembly.job \
     ${ROOT}/complex/reference.fa \
     ${ROOT}/complex/read_complex1.fa \
     ${OUTPUT}/complex1/ 3
qsub -o ./logfiles/complex2.log -j y ./script/disassembly.job \
     ${ROOT}/complex/reference.fa \
     ${ROOT}/complex/read_complex2.fa \
     ${OUTPUT}/complex2/ 3

