#!/bin/bash
#$ -S /bin/bash
#$ -N M4
#$ -cwd
#$ -pe smp 24
#$ -V
#$ -m e
set -ue 
REFERENCE=$1
READ=$2
OUTPUT=$3
CORES=24
MIN_CLUSTER=$4
LIMIT=${5:-6000}
ROOT=${PWD}

# ---- Clean up -----
rm -r ${OUTPUT}


# ---- Filtering ----
mkdir -p ${OUTPUT}/filtered_read
cd ../mito_assembler/
minimap2 -t 24 -x map-pb ${REFERENCE} ${READ} |\
    ./target/release/select_mito_reads ${READ} |\
    ./target/release/filter_low_quality > ${OUTPUT}/filtered_read/filtered_read.fa
READ=${OUTPUT}/filtered_read/filtered_read.fa



# ---- Alignment -----
mkdir -p ${OUTPUT}/last_db
cd ${OUTPUT}/last_db
lastdb -R00 -Q0 reference ${REFERENCE}
last-train -P${CORES} -Q0 reference ${READ} > score.matrix
lastal -f maf -P${CORES} -R00 -Q0 -p score.matrix reference ${READ} |\
    last-split | maf-convert tab --join 1000 > alignments.tab
last-train -P${CORES} -Q0 reference ${REFERENCE} > self.matrix
lastal -f tab -P${CORES} -R00 -Q0 -p self.matrix reference ${REFERENCE} > self.tab
cd ${ROOT}



# ----- Prediction ------
RUST_BACKTRACE=1 mmmm decompose --alignments ${OUTPUT}/last_db/alignments.tab --output ${OUTPUT} \
              --reads ${READ} --contigs ${REFERENCE} \
              --self_alignments ${OUTPUT}/last_db/self.tab \
              --cluster_num ${MIN_CLUSTER} --threads ${CORES} \
              --limit ${LIMIT}\
              -vv


# ---- Assembly(by Canu) ----
for reads in ${OUTPUT}/*.fasta
do
    ASM_PATH=${reads%%.fasta}
    INDEX=${ASM_PATH##*/}
    mkdir -p ${ASM_PATH}
    flye \
        --pacbio-raw \
        $reads \
	    --genome-size 200K \
        --threads ${CORES} \
        --iterations 10 \
        --plasmids \
        --out-dir $ASM_PATH 
done


# ---- Align back all reads ----
cargo run --release --bin collect_contigs -- ${OUTPUT}
for contigs in ${OUTPUT}*.contigs.fasta
do
    reads=${contigs%%.contigs.fasta}.fasta
    cd ${OUTPUT}/last_db
    lastdb -R00 temp ${contigs}
    last-train -P${CORES} -Q0 temp ${reads} > temp.matrix
    lastal -f maf -P${CORES} -R00 -Q0 -p temp.matrix temp ${reads} |\
        last-split | maf-convert tab --join 1000 > ${reads%%.fasta}.reads.aln.tab
    last-train -P${CORES} -Q0 reference ${contigs} > temp.matrix
    lastal -f tab -P ${CORES} -R00 -Q0 -p temp.matrix reference ${contigs} \
           > ${contigs%%.fasta}.aln.tab
    cd ${ROOT}
done

cat ${OUTPUT}/*.reads.aln.tab > ${OUTPUT}/reads.aln.tab
cat ${OUTPUT}/*.contigs.aln.tab > ${OUTPUT}/contigs.aln.tab



# ---- Create viewer files -----
mmmm create_viewer --assignments ${OUTPUT}/readlist.tsv \
     --contig_aln ${OUTPUT}/contigs.aln.tab \
     --contigs ${OUTPUT}/contigs.fasta \
     --output_dir ${OUTPUT}/viewer/ \
     --read_aln ${OUTPUT}/reads.aln.tab \
     --reads ${READ} \
     --reference ${REFERENCE}


