#!/bin/bash
#$ -S /bin/bash
#$ -N ResumeM4
#$ -pe smp 1
#$ -o ./logfiles/resume.log
#$ -j y
#$ -cwd
#$ -V
#$ -m e
set -ue

REFERENCE=${PWD}/data/NC_037304_1.fa
READ=${PWD}/result/kyo/filtered_read/filtered_read.fa
OUTPUT=${PWD}/result/kyo/
RESUME=${PWD}/result/kyo_resume/
CORES=12
ROOT=${PWD}

if [ -d ${RESUME} ]
then
    rm -r ${RESUME}
fi

### ---- Decompose --- 
RUST_BACKTRACE=full mmmm resume --alignments ${OUTPUT}/last_db/alignments.tab \
     --output ${RESUME} \
     --reads ${READ} --contigs ${REFERENCE} \
     --self_alignments ${OUTPUT}/last_db/self.tab \
     --dump_file ${PWD}/logfiles/kyo.log\
     -vv
exit 0;

# ---- Assembly(by Flye) ----
for reads in $( find ${RESUME} -maxdepth 1 -name "*.fasta")
do
    ASM_PATH=${reads%%.fasta}
    INDEX=${ASM_PATH##*/}
    mkdir -p ${RESUME}/assemblies/${INDEX}
    genomesize=$(cargo run --release --bin estimate_genome_size -- ${reads} ${REFERENCE} ${OUTPUT}/last_db/alignments.tab ${RESUME}/assemblies/${INDEX}/temp.fa)
    flye \
        --pacbio-raw \
        ${RESUME}/assemblies/${INDEX}/temp.fa \
	    --genome-size ${genomesize} \
        --threads ${CORES} \
        --iterations 10 \
        --out-dir ${RESUME}/assemblies/${INDEX}
    rm ${RESUME}/assemblies/${INDEX}/temp.fa
done

# ---- Align back all reads ----
mkdir ${RESUME}/last_db
cp ${REFERENCE} ${RESUME}/last_db
lastdb -R00 reference ${REFERENCE}
cargo run --release --bin collect_contigs -- ${RESUME}/assemblies/ ${RESUME}
for contigs in  $( find ${RESUME} -maxdepth 1 -name "*contigs.fasta" )
do
    reads=${contigs%%.contigs.fasta}.fasta
    cd ${RESUME}/last_db
    lastdb -R00 temp ${contigs}
    last-train -P${CORES} -Q0 temp ${reads} > temp.matrix
    lastal -f maf -P${CORES} -R00 -Q0 -p temp.matrix temp ${reads} |\
        last-split | maf-convert tab --join 1000 > ${reads%%.fasta}.reads.aln.tab
    last-train -P${CORES} -Q0 reference ${contigs} > temp.matrix
    lastal -f tab -P ${CORES} -R00 -Q0 -p temp.matrix reference ${contigs} \
           > ${contigs%%.fasta}.aln.tab
    cd ${ROOT}
done

cat ${RESUME}/*.reads.aln.tab > ${RESUME}/allreads.aln.tab
cat ${RESUME}/*.contigs.aln.tab > ${RESUME}/allcontigs.aln.tab
rm ${RESUME}/*.reads.aln.tab ${RESUME}/*.contigs.aln.tab


# ---- Create viewer files -----
mmmm create_viewer --assignments ${RESUME}/readlist.tsv \
     --contig_aln ${RESUME}/allcontigs.aln.tab \
     --contigs ${RESUME}/multipartite.fasta \
     --output_dir ${RESUME}/viewer/ \
     --read_aln ${RESUME}/allreads.aln.tab \
     --reads ${READ} \
     --reference ${REFERENCE}
