#!/bin/bash
#$ -S /bin/bash
#$ -N ResumeM4
#$ -o ./logfiles/pacbio_resume.log
#$ -j y
#$ -cwd
#$ -V
#$ -m e
set -ue
REFERENCE=${PWD}/data/NC_037304_1_split.fa
RESUME_DIR=${PWD}/result/pacbio
mmmm resume --alignments ${RESUME_DIR}/last_db/alignments.tab\
     --dump_file ${PWD}/logfiles/pacbio.log\
     --output ${PWD}/result/pacbio_resume/\
     --reads ${RESUME_DIR}/filtered_read/filtered_read.fa\
     --contigs ${REFERENCE}\
     --self_alignments ${RESUME_DIR}/last_db/self.tab\
     -vv
