#!/bin/bash
#$ -S /bin/bash
#$ -N debug
#$ -cwd
#$ -pe smp 1
#$ -e ./logfiles/log
#$ -o ./result/summary.txt
#$ -V
#$ -m e
set -ue 
SAM=/grid/ban-m/arabidopsis_thaliana/sequel/mapping/sequel_minimap2.sam
QUERY=/data/ban-m/a_thaliana/sequel_reads/sequel1_filter_dedupe.fq
REF=/grid/ban-m/arabidopsis_thaliana/genome/GCF_000001735.4_TAIR10.1_genomic.fna
MITO=NC_037304.1
CHR1=NC_003070.9

OUT=./result/mitochondria/
mkdir -p ${OUT}
echo "MITOCHONDRIA..."
/usr/bin/time -v cargo run --release -- ${SAM} ${QUERY} ${REF} ${OUT} ${MITO} > ${OUT}/log
OUT=./result/chr1
mkdir -p ${OUT}
echo "CHR NO 1..."
/usr/bin/time -v cargo run --release -- ${SAM} ${QUERY} ${REF} ${OUT} ${CHR1} > ${OUT}/log

