#!/bin/bash
#$ -S /bin/bash
#$ -N Canu
#$ -cwd
#$ -pe smp 1
#$ -e ./logfiles/canu.log
#$ -o ./logfiles/canu.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job
SEQUEL=/data/ban-m/a_thaliana/sequel_reads/sequel1.fq
ONT=/data/ban-m/a_thaliana/ONT/ERR2173373.fastq


set -ue

function canu_assemble () {
    canu \
	    genomeSize=135m \
        gridEngineMemoryOption="-l mem_free=MEMORY" \
        gridOptions="-S /bin/bash -V" \
        -d $1 -p $2 $3 $4
}

echo "sequel"
OUTPUT=/grid/ban-m/arabidopsis_thaliana/sequel/assemble/canu/
mkdir -p ${OUTPUT}
cd ${OUTPUT}
canu_assemble ${OUTPUT} canu_sequel -pacbio-raw ${SEQUEL} 

echo "nanopore"
OUTPUT=/grid/ban-m/arabidopsis_thaliana/nanopore/assemble/canu/
mkdir -p ${OUTPUT}
cd ${OUTPUT}
canu_assemble ${OUTPUT} canu_nanopore -nanopore-raw ${ONT} 
