#!/bin/bash
#$ -S /bin/bash
#$ -N Ra
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/ra.log
#$ -o ./logfiles/ra.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job
OUTPUT=/grid/ban-m/arabidopsis_thaliana/sequel/assemble/ra/
SEQUEL=/data/ban-m/a_thaliana/sequel_reads/sequel1.fq
ONT=/data/ban-m/a_thaliana/ONT/ERR2173373.fastq
mkdir -p ${OUTPUT}
cd ${OUTPUT}
ra -t 24 -x pb ${SEQUEL} > ./ra_sequel_contigs.fa

OUTPUT=/grid/ban-m/arabidopsis_thaliana/nanopore/assemble/ra/
mkdir -p ${OUTPUT}
cd ${OUTPUT}
ra -t 24 -x ont ${ONT} > ./ra_ont_contigs.fa
