#!/bin/bash
#$ -S /bin/bash
#$ -N Wtdbg
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/wtdbg.log
#$ -o ./logfiles/wtdbg.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job

set -ue
SAMTOOLS=/home/ban-m/local/bin/samtools

function assembly () {
    OUTPUT=$1
    READ=$2
    NAME=wtdbg_$3
    MINIMAP=$4
    mkdir -p ${OUTPUT}          
    cd ${OUTPUT}
    # cat ${READ} | paste - - - - | cut -f1-2 | sed -e 's/@/>/g' | tr '\t' '\n' > reads.fa
    # Assembly
    # wtdbg2 -fo ${NAME} -t 24 -x ${3} -g 135m -i reads.fa 
    # Consensus
    # gunzip -f ${NAME}.ctg.lay.gz
    # wtpoa-cns -t 24 -i ${NAME}.ctg.lay -fo ${NAME}.ctg.lay.fa
    # Polishing
    ${MINIMAP} ${NAME}.ctg.lay.fa reads.fa > ${NAME}.ctg.lay.map.paf
    racon -t 24 reads.fa ${NAME}.ctg.lay.map.paf ${NAME}.ctg.lay.fa > ${NAME}.ctg.lay.2nd.fa
}

# assembly /grid/ban-m/arabidopsis_thaliana/sequel/assemble/wtdbg/ \
#          /data/ban-m/a_thaliana/sequel_reads/sequel1.fq \
#          sequel \
#          "minimap2 -t 24 -x map-pb"

assembly /grid/ban-m/arabidopsis_thaliana/nanopore/assemble/wtdbg/ \
         /data/ban-m/a_thaliana/ONT/ERR2173373.fastq \
         nanopore \
         "minimap2 -t 24 -x map-ont"
