#!/bin/bash
#$ -S /bin/bash
#$ -N dilute
#$ -cwd
#$ -pe smp 20
#$ -e ./logfiles/dilute.log
#$ -o ./logfiles/dilute.log
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
set -ue

## Variables.
coverage=70
file=/data/ban-m/a_thaliana/sequel_reads/sequel1_filter_dedupe.fq
prefix=/grid/ban-m/arabidopsis_thaliana/sequel/dilution_onthefly2/
annotation=./result/sequel_to_reference.tsv

## Prep
mkdir -p ${prefix}
# rm ${prefix}/*

## 1 st iteration.
t=10
select_name=./result/selected.tsv
for i in $(seq ${t})
do
    echo ""
    # cargo run --release --bin dilute -- ${file} ${coverage} ${prefix}/${i}
done
Rscript --vanilla --slave ./script/select_based_on_global_cov.R "${prefix}*.tsv" ${annotation} ${select_name}
cargo run --release --bin select -- ${select_name} ${file} > ${prefix}/selected.fq


## 2 nd iteration
### Filtering binary
select_name=./result/selected_2nd.tsv
current=${PWD}
cd ../select_mitochondrial_genome/
cargo build --release
AVE_COV=${PWD}/target/release/average_coverage_from_stdin
cd ${current}

minimap2 -x ava-pb -t 12 ${prefix}/selected.fq ${prefix}/selected.fq |\
    ${AVE_COV} > ${prefix}/2nd_coverage.tsv
Rscript --vanilla --slave ./script/2nd_plot.R ${prefix}/2nd_coverage.tsv ${annotation} ${select_name}
cargo run --release --bin select -- ${select_name} ${file} | cargo run --release --bin rename > ${prefix}/selected_2nd.fq

## Finally
minimap2 -a -x ava-pb -t 12 ${prefix}/selected_2nd.fq ${prefix}/selected_2nd.fq > ${prefix}/selected_2nd.sam
