#!/bin/bash
#$ -S /bin/bash
#$ -N Baseline
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/baseline.log
#$ -o ./logfiles/baseline.out
#$ -V
#$ -m e
set -ue
ROOT=${PWD}
DATA=${PWD}/data/synthetic_data
OUTPUT=${PWD}/result/synthetic_data/baseline
for file in 100_001 50_001 150_001
do
    LOGFILE=${PWD}/logfiles/${file}_time.log
    read=${DATA}/${file}/${file}_reads.fq
    reference=${DATA}/${file}/${file}_reference.fa
    echo "isONclust" > ${LOGFILE}
    date >> ${LOGFILE}
    isONclust --ont --fastq ${read} --outfolder ${OUTPUT}/${file}/isONclust
    date >> ${LOGFILE}
    mkdir -p ${OUTPUT}/${file}/whatshap
    BAM=${OUTPUT}/${file}/whatshap/${file}.bam
    CAND=${OUTPUT}/${file}/whatshap/${file}_cand.vcf
    GENOTYPE=${OUTPUT}/${file}/whatshap/${file}_genot.vcf
    PHASED=${OUTPUT}/${file}/whatshap/${file}_phased.vcf.gz
    PHASED_BAM=${OUTPUT}/${file}/whatshap/${file}.phased.bam
    RESULT=${OUTPUT}/${file}/whatshap/${file}.tsv
    echo "WHATSHAP" >> ${LOGFILE}
    date >> ${LOGFILE}
    minimap2 -a -t 24 -x map-pb ${reference} ${read} |\
        samtools sort -O BAM -m2G -@3 > ${BAM}
    samtools index ${BAM}
    whatshap find_snv_candidates --multi-allelics -o ${CAND} --pacbio \
             ${reference}  ${BAM}
    whatshap genotype --ignore-read-groups --reference ${reference} \
             ${CAND} ${BAM} > ${GENOTYPE}
    whatshap phase --ignore-read-groups --indels --reference ${reference} \
             -o ${PHASED} ${GENOTYPE} ${BAM}
    tabix -p vcf ${PHASED}
    whatshap haplotag -o ${PHASED_BAM} --ignore-read-groups \
             --reference ${reference} ${PHASED} ${BAM} \
             --output-haplotag-list ${RESULT}
    date >> ${LOGFILE}
    echo "CARNAC_LR" >> ${LOGFILE}
    date >> ${LOGFILE}
    mkdir -p ${OUTPUT}/${file}/carnac
    minimap2 -t 24 ${read} ${read} -X -x ava-pb > ${OUTPUT}/${file}/carnac/ava.paf
    python ${ROOT}/script/paf_to_CARNAC.py \
           ${OUTPUT}/${file}/carnac/ava.paf \
           ${read} ${OUTPUT}/${file}/carnac/carnac_input.txt
    CARNAC-LR -f ${OUTPUT}/${file}/carnac/carnac_input.txt \
              -o ${OUTPUT}/${file}/carnac/carnac_output.txt \
              -t 24
    date >> ${LOGFILE}
    flye --pacbio-raw ${read} --threads 24 --meta --genome-size 2M \
         --out-dir ${OUTPUT}/${file}/flye/
done
