#!/bin/bash
#$ -S /bin/bash
#$ -N decompose
#$ -cwd
#$ -pe smp 1
#$ -e ./logfiles/enumerate_cr.log
#$ -o ./logfiles/enumerate_cr.log
#$ -V
#$ -m e
READ=../disassembly/result/pacbio/filtered_read/filtered_read.fa
ALIGN=../disassembly/result/pacbio/last_db/alignments.tab
CONTIG=../disassembly/data/NC_037304_1.fa
REPEAT=../disassembly/result/pacbio/last_db/self.tab
cargo run --release --bin enumerate_cr -- ${READ} ${ALIGN} ${CONTIG} ${REPEAT} \
      > ./logfiles/cr.json 2> ./logfiles/cr.log

