#!/bin/bash
#$ -S /bin/bash
#$ -N readcov
#$ -e ./logfiles/calc_positionwise_coverage.log
#$ -cwd
#$ -o ./logfiles/calc_positionwise_coverage.out
#$ -V
#$ -pe smp 24
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job
## "-S" specifies which shell do the script run on.
## "-N" specifies the name of the job(should NOT be TEMPLATE).
## "-cwd" means the script run on the current directly, not on $HOME.
## "-pe smp N" specifies the number of the core the script requires.
## with "-e [path]", the stderr would be written in [path], not ${HOME}/$JOB_NUMBER
## with "-o [path]" is the same as "-e", except for stdout.
## with "-V", all envirnmental variables would be inherited.
## "with -m e", a mail would be sent if the job halt with an error.
## For more detail, see `man qsub`

SEQUEL=/grid/ban-m/arabidopsis_thaliana/sequel/mapping/sequel_minimap2_allvsall.paf
ONT=/grid/ban-m/arabidopsis_thaliana/nanopore/mapping/nanopore_minimap2_allvsall.paf
START=./result/sequel_positionwise_start.csv
STOP=./result/sequel_positionwise_stop.csv

# cargo run --release \
#       --bin stst_reads_positionwise \
#       -- ${SEQUEL} ${START} ${STOP}

cargo run --release \
      --bin pick_exampler_from_stst \
      -- ${START} ${STOP} \
      ./result/sequel_minimap2_assignment.tsv \
      ${START%.csv}.pick.csv ${STOP%.csv}.pick.csv \
