#!/bin/bash
#$ -S /bin/bash
#$ -N readcov
#$ -cwd
#$ -pe smp 12
#$ -e ./logfiles/calc_positionwise_coverage.log
#$ -o ./logfiles/calc_positionwise_coverage.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job
## "-S" specifies which shell do the script run on.
## "-N" specifies the name of the job(should NOT be TEMPLATE).
## "-cwd" means the script run on the current directly, not on $HOME.
## "-pe smp N" specifies the number of the core the script requires.
## with "-e [path]", the stderr would be written in [path], not ${HOME}/$JOB_NUMBER
## with "-o [path]" is the same as "-e", except for stdout.
## with "-V", all envirnmental variables would be inherited.
## "with -m e", a mail would be sent if the job halt with an error.
## For more detail, see `man qsub`

SEQUEL=/grid/ban-m/arabidopsis_thaliana/sequel/mapping/sequel_minimap2_allvsall.paf
ONT=/grid/ban-m/arabidopsis_thaliana/nanopore/mapping/nanopore_minimap2_allvsall.paf

cargo run --release \
      --bin positionwise_coverage ${SEQUEL} > \
      ./result/sequel_positionwise_coverage.tsv

cargo run --release \
      --bin pick_exampler_from_coverage \
      -- ./result/sequel_positionwise_coverage.tsv \
      ./result/sequel_minimap2_assignment.tsv \
      > ./result/sequel_positionwise_coverage_short.tsv

Rscript --vanilla --slave ./script/local_coverage_plot.R \
        ./result/sequel_positionwise_coverage.tsv \
        ./result/sequel_minimap2_assignment.tsv
