#!/bin/bash
#$ -S /bin/bash
#$ -N SamToAnnot
#$ -cwd
#$ -pe smp 1
#$ -e ./logfiles/SAM_to_annotation.log
#$ -o ./logfiles/SAM_to_annotation.log
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job
## "-S" specifies which shell do the script run on.
## "-N" specifies the name of the job(should NOT be TEMPLATE).
## "-cwd" means the script run on the current directly, not on $HOME.
## "-pe smp N" specifies the number of the core the script requires.
## with "-e [path]", the stderr would be written in [path], not ${HOME}/$JOB_NUMBER
## with "-o [path]" is the same as "-e", except for stdout.
## with "-V", all envirnmental variables would be inherited.
## "with -m e", a mail would be sent if the job halt with an error.
## For more detail, see `man qsub`

MAPPINGS=/grid/ban-m/arabidopsis_thaliana/sequel/mapping/sequel_minimap2.bam
samtools view ${MAPPINGS} | \
    awk '(and($2,0x900) == 0x00){print $0}' | \
    cut -f 1,3 > ./result/sequel_minimap2_assignment.tsv
