#!/bin/bash
#$ -S /bin/bash
#$ -N AvAMinialign
#$ -cwd
#$ -pe smp 12
#$ -e ./logfiles/minialign.log
#$ -o ./logfiles/minialign.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job

ONT=/data/ban-m/a_thaliana/ONT/ERR2173373.fastq
ONT_OUTPUT=/grid/ban-m/arabidopsis_thaliana/nanopore/mapping

SEQUEL=/data/ban-m/a_thaliana/sequel_reads/sequel1_filter_dedupe.fq
SEQUEL_OUTPUT=/grid/ban-m/arabidopsis_thaliana/sequel/mapping

mkdir -p ${SEQUEL_OUTPUT}
minialign -t 12 -X -xpacbio ${SEQUEL} > ${SEQUEL_OUTPUT}/sequel_minialign_allvsall.sam

mkdir -p ${ONT_OUTPUT}
minialign -t 12 -X -xont.r9 ${ONT} > ${ONT_OUTPUT}/nanopore_minialign_allvsall.sam



