#!/bin/bash
#$ -S /bin/bash
#$ -N AvAMinialign
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/ava-minimap2.log
#$ -o ./logfiles/ava-minimap2.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job

ONT=/data/ban-m/a_thaliana/ONT/ERR2173373.fastq
ONT_OUTPUT=/grid/ban-m/arabidopsis_thaliana/nanopore/mapping

SEQUEL=/data/ban-m/a_thaliana/sequel_reads/sequel1_filter_dedupe.fq
SEQUEL_OUTPUT=/grid/ban-m/arabidopsis_thaliana/sequel/mapping

mkdir -p ${SEQUEL_OUTPUT}
minimap2 -t 24 -X -x ava-pb ${SEQUEL} ${SEQUEL} > ${SEQUEL_OUTPUT}/sequel_minimap2_allvsall.paf

# mkdir -p ${ONT_OUTPUT}
# minimap2 -a -t 12 -X -x ava-ont ${ONT} ${ONT} | \
#     samtools view -bhS > ${ONT_OUTPUT}/nanopore_minimap2_allvsall.bam



