#!/bin/bash
#$ -S /bin/bash
#$ -N kmer
#$ -cwd
#$ -pe smp 12
#$ -e ./logfiles/kmer-frequency.log
#$ -o ./logfiles/kmer-frequency.out
#$ -V
#$ -m e

ONT=/data/ban-m/a_thaliana/ONT/ERR2173373.fasta
SEQUEL=/data/ban-m/a_thaliana/sequel_reads/sequel1_filter_dedupe.fa

function proc() {
    K=${3}
    jellyfish count -s 4G --bf-size 50G -m ${K} -t 24 -o $2.jf -L 20 $1
    jellyfish histo -o $2.hist $2.jf 
}
cd ./result/
# for K in 10 11 12 13 14 15 18 20 22
# do
#     proc ${ONT} ont_${K}mer ${K}
#     proc ${SEQUEL} sequel_${K}mer ${K}
# done
for K in 30 50 80 100 150
do
    proc ${ONT} ont_${K}mer ${K}
    proc ${SEQUEL} sequel_${K}mer ${K}
done

cd ../
for file in ./result/*.hist
do
    Rscript --vanilla --slave ./script/plot_histogram.R ${file}
done
mv ./result/*.png ./png/
