#!/bin/bash
#$ -S /bin/bash
#$ -N mapping_compare
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/mapping.log
#$ -o ./logfiles/mapping.out
#$ -V
#$ -m e
# -M banmasutani@gmail.com ## To send a mail when ended
# -t 1:n ## For array job

ONT=/data/ban-m/a_thaliana/ONT/ERR2173373.fastq
ONT_OUTPUT=/grid/ban-m/arabidopsis_thaliana/nanopore/mapping

SEQUEL=/data/ban-m/a_thaliana/sequel_reads/sequel1_filter_dedupe.fq
SEQUEL_OUTPUT=/grid/ban-m/arabidopsis_thaliana/sequel/mapping
REFERENCE=/grid/ban-m/arabidopsis_thaliana/genome/GCF_000001735.4_TAIR10.1_genomic.fna

function stat () {
    OUTPUT=${1%.sam}
    samtools view -hSb $1 |\
        samtools sort -@ 24 -m 5G -O BAM > ${OUTPUT}.bam
    samtools stats ${OUTPUT}.bam > ${OUTPUT}.stat
}


# mkdir -p ${SEQUEL_OUTPUT}
# minialign -t 24 -xpacbio.clr ${REFERENCE} ${SEQUEL} > ${SEQUEL_OUTPUT}/sequel_minialign.sam
minimap2 -a -t 24 -x map-pb ${REFERENCE} ${SEQUEL} > ${SEQUEL_OUTPUT}/sequel_minimap2.sam

# mkdir -p ${ONT_OUTPUT}
# minialign -t 24 -xont.r9.1d ${REFERENCE} ${ONT} > ${ONT_OUTPUT}/nanopore_minialign.sam
minimap2 -a -t 24 -x map-ont ${REFERENCE} ${ONT} > ${ONT_OUTPUT}/nanopore_minimap2.sam

stat ${SEQUEL_OUTPUT}/sequel_minialign.sam
stat ${SEQUEL_OUTPUT}/sequel_minimap2.sam

stat ${ONT_OUTPUT}/nanopore_minialign.sam
stat ${ONT_OUTPUT}/nanopore_minimap2.sam

