#!/bin/bash
#$ -S /bin/bash
#$ -N kmercount
#$ -cwd
#$ -pe smp 24
#$ -e ./logfiles/kmercount.log
#$ -o ./logfiles/kmercount.out
#$ -V
#$ -m e

BEFORE_CORRECTION=/grid/ban-m/arabidopsis_thaliana/sequel/dilution_onthefly2/selected_2nd.fq
CORRECTION=/grid/ban-m/arabidopsis_thaliana/sequel/dilution_onthefly2/corrected.fq
for k in 50 150
do
    cargo run --release --bin native -- ${BEFORE_CORRECTION} ${k} > ./result/before.${k}.tsv
    cargo run --release --bin native -- ${CORRECTION} ${k} > ./result/after.${k}.tsv
    cargo run --release --bin run_length_compress -- ${CORRECTION} ${k} > ./result/before.${k}.compress.tsv
    Rscript --vanilla --slave ./script/plot.R ./result/before.${k}.tsv ./png/before.${k}.png
    Rscript --vanilla --slave ./script/plot.R ./result/after.${k}.tsv ./png/after.${k}.png
    Rscript --vanilla --slave ./script/plot.R ./result/after.${k}.compress.tsv ./png/after.${k}.compress.png
done
